import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration from styles.css
const VIEWPORT_MIN = 20; // 320px
const VIEWPORT_MAX = 110; // 1760px
const PIXELS_PER_REM = 16;

// Helper to round to 4 decimal places
const round = (num) => Math.round(num * 10000) / 10000;

// Logic from fluid-builder/bundle.js (adapted for Node)
function getClamp(minSizeRem, maxSizeRem, minWidthRem = VIEWPORT_MIN, maxWidthRem = VIEWPORT_MAX) {
    const minWidth = minWidthRem * PIXELS_PER_REM;
    const maxWidth = maxWidthRem * PIXELS_PER_REM;
    const minSize = minSizeRem * PIXELS_PER_REM;
    const maxSize = maxSizeRem * PIXELS_PER_REM;

    const slope = (maxSize - minSize) / (maxWidth - minWidth);
    const yAxisIntersection = -minWidth * slope + minSize;

    const slopeVw = round(slope * 100);
    const interceptRem = round(yAxisIntersection / PIXELS_PER_REM);

    // clamp(MIN, VAL, MAX)
    // VAL = slope * 100vw + intercept
    return `clamp(${minSizeRem}rem, ${interceptRem}rem + ${slopeVw}vw, ${maxSizeRem}rem)`;
}

// Type Scale Definition (min -> max in rem)
// Using a ratio (e.g., 1.2 for min, 1.33 for max) or manual values
// Legacy/Project Specific Variables
const legacyTypography = {
    '--typography-font-size-text-small': [0.875, 1],
    '--typography-font-size-text-main': [1, 1.125],
    '--typography-font-size-large': [1.125, 1.25],
    '--typography-font-size-h5': [1.375, 1.5],
    '--typography-font-size-h4': [1.75, 2],
    '--typography-font-size-h3': [2.25, 3],
    '--typography-font-size-h2': [2.5, 4],
    '--typography-font-size-h1': [3, 5],
    '--typography-font-size-display': [6, 10],
};

const legacySpacing = {
    // Section Spacing
    '--spacing-section-space-small': [3, 5],
    '--spacing-section-space-medium': [4, 7],
    '--spacing-section-space-large': [5.5, 10],
    '--spacing-section-space-page-top': [10, 14],

    // Site Layout
    '--site--margin': [1, 3],
    '--site--gutter': [1, 2],

    // Spacing Scale
    '--spacing-space-1': [0.375, 0.5],
    '--spacing-space-2': [0.625, 0.75],
    '--spacing-space-3': [0.875, 1],
    '--spacing-space-4': [1.25, 1.5],
    '--spacing-space-5': [1.75, 2],
    '--spacing-space-6': [2, 2.5],
    '--spacing-space-7': [2.25, 3],
    '--spacing-space-8': [2.5, 4],
    '--spacing-space-9': [2.75, 4],
    '--spacing-space-10': [3, 4],
};


// Type Scale Definition (min -> max in rem)
// Using a ratio (e.g., 1.2 for min, 1.33 for max) or manual values
const typeScale = {
    '--text-xs': [0.75, 0.875],
    '--text-sm': [0.875, 1],
    '--text-base': [1, 1.125],
    '--text-lg': [1.125, 1.25],
    '--text-xl': [1.25, 1.5],
    '--text-2xl': [1.5, 2],
    '--text-3xl': [1.875, 3],
    '--text-4xl': [2.25, 4],
    '--text-5xl': [3, 5],
    '--text-6xl': [3.75, 6],
    '--text-7xl': [4.5, 7],
    '--text-8xl': [6, 8],
    '--text-9xl': [8, 10],
};

// Spacing Scale Definition
const spacingScale = {
    '--space-3xs': [0.25, 0.5],
    '--space-2xs': [0.5, 0.75],
    '--space-xs': [0.75, 1],
    '--space-sm': [1, 1.5],
    '--space-md': [1.5, 2],
    '--space-lg': [2, 3],
    '--space-xl': [3, 4],
    '--space-2xl': [4, 6],
    '--space-3xl': [6, 9],
    '--space-4xl': [8, 12],
    '--space-section-sm': [3, 5],
    '--space-section-md': [5, 8],
    '--space-section-lg': [8, 12],
    '--space-section-xl': [10, 15],
};

// One-off specific variables requested or common
const miscScale = {
    // '--site-gutter': [1, 2], // moved to legacy
    // '--site-margin': [1, 3], // moved to legacy
    '--container-padding': [1, 3],
}

let cssContent = `/* Fluid Typography & Spacing System */
/* Generated by scripts/fluid-system.js */
:root {
  /* Viewports */
  --fluid-viewport-min: ${VIEWPORT_MIN}rem;
  --fluid-viewport-max: ${VIEWPORT_MAX}rem;

  /* Project Typography */
`;

for (const [name, [min, max]] of Object.entries(legacyTypography)) {
    cssContent += `  ${name}: ${getClamp(min, max)};\n`;
}

cssContent += `\n  /* Project Spacing */\n`;
for (const [name, [min, max]] of Object.entries(legacySpacing)) {
    cssContent += `  ${name}: ${getClamp(min, max)};\n`;
}

cssContent += `\n  /* System Typography (Extensive) */\n`;
for (const [name, [min, max]] of Object.entries(typeScale)) {
    cssContent += `  ${name}: ${getClamp(min, max)};\n`;
}

cssContent += `\n  /* System Spacing (Extensive) */\n`;
for (const [name, [min, max]] of Object.entries(spacingScale)) {
    cssContent += `  ${name}: ${getClamp(min, max)};\n`;
}

cssContent += `\n  /* Misc */\n`;
for (const [name, [min, max]] of Object.entries(miscScale)) {
    cssContent += `  ${name}: ${getClamp(min, max)};\n`;
}

cssContent += `}\n`;

const outputPath = path.resolve(__dirname, '../fluid-type.css');
fs.writeFileSync(outputPath, cssContent);
console.log(`Fluid type CSS written to ${outputPath}`);
